requires:
- category: "dev-util"
  name: "mottainai-server"
  version: ">=0"
env:
- GOPATH=/luetbuild/go/
steps:
- cd go/src/github.com/${GITHUB_ORG}/mottainai-server/{{ .Values.name }}/ && mv {{ .Values.name }} /usr/bin/{{ .Values.name }}
includes:
- /usr/bin/mottainai-cli
