image: "quay.io/mocaccino/extra"
prelude:
- luet install development/make lang/go vcs/git
- mkdir go/src/github.com/${GITHUB_ORG}/ -p
- cd go/src/github.com/${GITHUB_ORG}/ && git clone https://github.com/${GITHUB_ORG}/${PACKAGE_NAME}.git
env:
- GOPATH=/luetbuild/go/
- GITHUB_ORG=MottainaiCI
- GIT_HASH=ea31787c84fa345f5a5ee58822b2526b8b459ef0
steps:
- cd go/src/github.com/${GITHUB_ORG}/${PACKAGE_NAME} && git checkout "${GIT_HASH}" && make build && mv ${PACKAGE_NAME} /usr/bin/${PACKAGE_NAME}
includes:
- /usr/bin/replicant
