requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /docker
env:
- DOCKER_ARCH=x86_64

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   if [ "${MUSL_ARCH}" == "arm" ] ; then DOCKER_ARCH=armhf ; fi && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   curl -L https://download.docker.com/linux/static/stable/${DOCKER_ARCH}/docker-${PACKAGE_VERSION}.tgz -o docker.tgz && \
   tar -xvf docker.tgz && cp -rfv docker/* /${PACKAGE_NAME}/usr/bin/
