image: "alpine"
package_dir: /packer
prelude:
- apk add zip curl
steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   curl -L https://releases.hashicorp.com/packer/${PACKAGE_VERSION}/packer_${PACKAGE_VERSION}_linux_amd64.zip -o packer.zip && unzip packer.zip && mv packer /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
