image: "quay.io/mocaccino/micro:master"

package_dir: /keybase-tools
env:
- LUET_YES=true
- LUET_NOLOCK=true

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   cp -rfv keybase-*  /${PACKAGE_NAME}/usr/bin/ && \
   rm -rf /${PACKAGE_NAME}/usr/bin/*.dockerfile && \
   chmod +x /${PACKAGE_NAME}/usr/bin/keybase-*
