requires:
- name: "toolchain-go"
  category: "development"
  version: ">=1.18"
prelude:
- mkdir go/src/github.com/${GITHUB_ORG}/ -p
- cd go/src/github.com/${GITHUB_ORG}/ && git clone https://github.com/${GITHUB_ORG}/{{ .Values.name }}.git
env:
- GOPATH=/luetbuild/go/
- GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
- CGO_ENABLED=0
steps:
- cd go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/  && git checkout v"${PACKAGE_VERSION}" -b build && make build && mv build/* /usr/bin/
- chmod +x /usr/bin/upterm
- chmod +x /usr/bin/uptermd
includes:
- /usr/bin/upterm
- /usr/bin/uptermd
