{{ $org:= ( index .Values.labels "github.owner" ) }}
{{ $repo:= ( index .Values.labels "github.repo" ) }}
{{ $opts:= dict "org" $org "repo" $repo }}
{{ template "golang_build" $opts}}
-  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   cd go/src/github.com/{{$org}}/{{$repo}}/ && git checkout "v${PACKAGE_VERSION}" -b build && ./build_dist.sh tailscale.com/cmd/tailscale && ./build_dist.sh tailscale.com/cmd/tailscaled && \
   mv {{ .Values.name }} /output/usr/bin/{{ .Values.name }} && \
   mv {{ .Values.name }}d /output/usr/bin/{{ .Values.name }}d
- chmod +x /output/usr/bin/{{ .Values.name }}
- chmod +x /output/usr/bin/{{ .Values.name }}d