{{ if eq .Values.arch "arm" }}
{{ if eq .Values.name "toolchain-go" }}
image: "golang:{{.Values.version}}-alpine"
{{ else }}
image: "alpine"
{{ end }}
prelude:
- apk update
- apk add curl make git bash
- curl -L https://github.com/mudler/luet/releases/download/0.20.10/luet-0.20.10-linux-armv7 --output /usr/bin/luet
- chmod +x /usr/bin/luet
- LUET_YES=true
{{ else }}
{{ if eq .Values.name "toolchain-go" }}
image: "golang:{{.Values.version}}-alpine"
prelude:
- apk update
- apk add curl make git bash
- curl -L https://github.com/mudler/luet/releases/download/0.20.10/luet-0.20.10-linux-amd64 --output /usr/bin/luet
- chmod +x /usr/bin/luet
- LUET_YES=true
{{ else }}
image: "quay.io/mocaccino/micro-toolchain:latest"
prelude:
- >-
  luet install
  libs/libressl utils/ca-certificates shells/bash
  utils/autoconf utils/curl development/make libs/zlib vcs/git
  development/automake development/pkg-config development/m4
  system/musl-compat
- luet cleanup
env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- LUET_YES=true
- LUET_FORCE=true
{{ end }}
{{ end }}
