{{ if eq .Values.arch "arm" }}
image: "quay.io/mocaccino/micro-toolchain:latest"
prelude:
- |
   luet install \
   utils/autoconf utils/curl development/make libs/zlib vcs/git \
   development/automake development/pkg-config development/m4 \
   system/musl-compat
env:
- MUSL_TARGET=armv7a-mocaccino-linux-musleabihf
- MUSL_ARCH=arm
- MUSL_CPU=armv7a
- MUSL_CPU_LD=armv7a
- LUET_YES=true

{{ else }}

image: "quay.io/mocaccino/micro-toolchain:latest"
prelude:
- >-
  luet install repository/mocaccino-micro-stable &&
  luet uninstall repository/mocaccino-micro &&
  luet install
  utils/autoconf utils/curl development/make libs/zlib vcs/git
  development/automake development/pkg-config development/m4
  system/musl-compat &&
  luet cleanup
env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- LUET_YES=true

{{ end }}
