requires:
- name: "toolchain-go"
  category: "development"
  version: ">=0"
prelude:
- >-
  git clone https://github.com/{{ ( index .Values.labels "github.repo" ) }}/{{ .Values.name }}.git
- >-
  cd {{ .Values.name }} && git checkout "${GIT_TAG%\+*}" &&
  make build &&
  mkdir /{{ .Values.name }}/usr/bin -p &&
  cp {{ .Values.name }} /{{ .Values.name }}/usr/bin/
env:
- GIT_TAG=v{{ .Values.version }}
- CGO_ENABLED=0
package_dir: /{{ .Values.name }}
