requires:
- category: "dev-util"
  name: "mottainai-server"
  version: ">=0"

env:
- GOPATH=/luetbuild/go/
package_dir: /mottainai-scheduler
steps:
# TODO: fix this with DESTDIR install on Makefile
- mkdir /${PACKAGE_NAME}
- mkdir -p /${PACKAGE_NAME}/usr/bin
- mkdir -p /${PACKAGE_NAME}/etc/mottainai
- mkdir -p /${PACKAGE_NAME}/etc/mottainai
- mkdir -p /${PACKAGE_NAME}/etc/mottainai/systemd/
- mkdir -p /${PACKAGE_NAME}/srv/mottainai
#- mkdir -p /${PACKAGE_NAME}/lib/systemd/system
- |
  cd ${GOPATH}/src/github.com/${GITHUB_ORG}/mottainai-server/${PACKAGE_NAME}/ && \
  mv ${PACKAGE_NAME} /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
  cp contrib/config/mottainai-scheduler.yaml.example /${PACKAGE_NAME}/etc/mottainai/mottainai-scheduler.yaml && \
  cp contrib/systemd/mottainai* /${PACKAGE_NAME}/etc/mottainai/systemd/

# cp contrib/systemd/mottainai* /${PACKAGE_NAME}/lib/systemd/system/
