image: golang
prelude:
- apt-get update
- apt-get install git
- git clone https://github.com/mudler/charty
steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  cd charty && git checkout "v${PACKAGE_VERSION}" && make deps multiarch-build && mv release/charty-*-linux-amd64 /usr/bin/charty
includes:
- /usr/bin/charty
