requires:
- category: "development"
  name: "toolchain"
  version: ">=0"


env:
- CFLAGS="-I/include -I/usr/include -static"
- LDFLAGS="-L/usr/lib -L/lib"

package_dir: /openssh
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf development/make development/automake vcs/git development/m4 libs/libressl && \
   mkdir -p /${PACKAGE_NAME} && \
   git clone https://github.com/${PACKAGE_NAME}/${PACKAGE_NAME}-portable ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && git checkout -b build V_${PACKAGE_VERSION//./_}_P1

steps:
- cd ${PACKAGE_NAME} && autoreconf
- cd ${PACKAGE_NAME} && ./configure --prefix=/usr
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install-nokeys
- cd ${PACKAGE_NAME} && make install-nokeys
