requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /integration
steps:
- mkdir -p /integration/usr/bin/
- mkdir -p /integration/etc/runit/core-services
- cp -rfv 13-yip.sh /integration/etc/runit/core-services/13-yip.sh
- chmod +x /integration/etc/runit/core-services/13-yip.sh
- mkdir -p /integration/etc/yip.d/
- cp -rfv yipfiles/*.yaml /integration/etc/yip.d/
- cp -rfv yip-init /integration/usr/bin/
- chmod +x /integration/usr/bin/yip-init