requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

env:
{{ if .Values.arch eq "arm" }}
- ARCH=armv7
{{ else }}
- ARCH={{.Values.arch}}
{{ end }}

package_dir: /{{.Values.name}}

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   curl -L https://github.com/screego/server/releases/download/v${PACKAGE_VERSION}/screego_${PACKAGE_VERSION}_linux_$ARCH.tar.gz -o archive.tar.gz && \
   tar xvf archive.tar.gz && mv ${PACKAGE_NAME} /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
