{{ if eq .Values.arch "amd64" }}
requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /{{.Values.name}}

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   curl -L https://github.com/esimov/triangle/releases/download/v${PACKAGE_VERSION}/triangle-$PACKAGE_VERSION-linux-{{.Values.arch}}.tar.gz | tar -xzvf - -C ./ && \
   mv triangle-$PACKAGE_VERSION-linux-{{.Values.arch}}/triangle /$PACKAGE_NAME/usr/bin/${PACKAGE_NAME} && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}

includes:
- /usr/bin/{{.Values.name}}
{{end}}