image: "alpine"
package_dir: /{{.Values.name}}
prelude:
- apk add zip curl
steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   curl -L https://releases.hashicorp.com/${PACKAGE_NAME}/${PACKAGE_VERSION}/${PACKAGE_NAME}_${PACKAGE_VERSION}_linux_{{.Values.arch}}.zip -o $PACKAGE_NAME.zip && \
   unzip $PACKAGE_NAME.zip && mv $PACKAGE_NAME /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
