image: "quay.io/mocaccino/extra"
requires:
- category: "users"
  name: "mottainai-agent"
  version: ">0"
- category: "groups"
  name: "mottainai"
  version: ">0"

prelude:
- luet install development/make lang/go vcs/git
- git clone https://github.com/MottainaiCI/${PACKAGE_NAME}.git
env:
- GIT_HASH=fef9fb3d651ef9dd39655d9b3fceec2132a70fd3
- LIB_DIR=/var/lib/mottainai
- SRV_DIR=/srv/mottainai
package_dir: /mottainai-agent
steps:
- cd ${PACKAGE_NAME} && git checkout "${GIT_HASH}" && make build
- mkdir /${PACKAGE_NAME}
- mkdir -p /${PACKAGE_NAME}/usr/bin
- mkdir -p /${PACKAGE_NAME}/etc/mottainai
- mkdir -p /${PACKAGE_NAME}${LIB_DIR}
- mkdir -p /${PACKAGE_NAME}${SRV_DIR}/build_temp
- mkdir -p /${PACKAGE_NAME}${SRV_DIR}/build/lxc
- mkdir -p /${PACKAGE_NAME}/lib/systemd/system
- mv ${PACKAGE_NAME} /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
- cp contrib/config/mottainai-agent.yaml.example /${PACKAGE_NAME}/etc/mottainai/mottainai-agent.yaml
- cp contrib/config/lxc/config.yml /${PACKAGE_NAME}${SRV_DIR}/build/lxc
- chmod a+x contrib/scripts/mottainai-lxd-cleanup-zombie-containers
- chmod a+x contrib/scripts/mottainai-lxd-cleanup-expired-cached-images
- cp contrib/scripts/mottainai-lxd-cleanup-zombie-containers /${PACKAGE_NAME}/usr/bin/
- cp contrib/scripts/mottainai-lxd-cleanup-expired-cached-images /${PACKAGE_NAME}/usr/bin/
- chown mottainai-agent:mottainai -R /${PACKAGE_NAME}${SRV_DIR}
- chmod -R 774 /${PACKAGE_NAME}${SRV_DIR}/build/lxc
- chmod -R 774 /${PACKAGE_NAME}${SRV_DIR}/build
- chmod -R 774 /${PACKAGE_NAME}${SRV_DIR}/build_temp
- cp contrib/systemd/mottainai* /${PACKAGE_NAME}/lib/systemd/system/
