requires:
- category: "dev-util"
  name: "mottainai-server"
  version: ">=0"
env:
- GOPATH=/luetbuild/go/
- LIB_DIR=/var/lib/mottainai
- SRV_DIR=/srv/mottainai
package_dir: /mottainai-agent
steps:
# TODO: fix this with DESTDIR install on Makefile
- mkdir /${PACKAGE_NAME}
- mkdir -p /${PACKAGE_NAME}/usr/bin
- mkdir -p /${PACKAGE_NAME}/etc/mottainai
- mkdir -p /${PACKAGE_NAME}${LIB_DIR}
- mkdir -p /${PACKAGE_NAME}${SRV_DIR}/build_temp
- mkdir -p /${PACKAGE_NAME}${SRV_DIR}/build/lxc
- mkdir -p /${PACKAGE_NAME}${SRV_DIR}/systemd
#- mkdir -p /${PACKAGE_NAME}/lib/systemd/system
- |
  cd ${GOPATH}/src/github.com/${GITHUB_ORG}/mottainai-server/${PACKAGE_NAME}/ && \
  mv ${PACKAGE_NAME} /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
  cp contrib/config/mottainai-agent.yaml.example /${PACKAGE_NAME}/etc/mottainai/mottainai-agent.yaml && \
  cp contrib/config/lxc/config.yml /${PACKAGE_NAME}${SRV_DIR}/build/lxc && \
  chmod a+x contrib/scripts/mottainai-lxd-cleanup-zombie-containers && \
  chmod a+x contrib/scripts/mottainai-lxd-cleanup-expired-cached-images && \
  cp contrib/scripts/mottainai-lxd-cleanup-zombie-containers /${PACKAGE_NAME}/usr/bin/ && \
  cp contrib/scripts/mottainai-lxd-cleanup-expired-cached-images /${PACKAGE_NAME}/usr/bin/ && \
  chmod -R 774 /${PACKAGE_NAME}${SRV_DIR}/build/lxc && \
  chmod -R 774 /${PACKAGE_NAME}${SRV_DIR}/build && \
  chmod -R 774 /${PACKAGE_NAME}${SRV_DIR}/build_temp && \
  cp contrib/systemd/mottainai* /${PACKAGE_NAME}${SRV_DIR}/systemd/

# cp contrib/systemd/mottainai* /${PACKAGE_NAME}/lib/systemd/system/
