requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /frp

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /frp/usr/bin && \
   curl -L https://github.com/fatedier/frp/releases/download/v${PACKAGE_VERSION}/frp_${PACKAGE_VERSION}_linux_{{.Values.arch}}.tar.gz -o frp.tar.gz && \
   tar xvf frp.tar.gz -C ./ && \
   mv frp_${PACKAGE_VERSION}_linux_{{.Values.arch}}/frpc /frp/usr/bin && \
   mv frp_${PACKAGE_VERSION}_linux_{{.Values.arch}}/frps /frp/usr/bin && \
   chmod +x /frp/usr/bin/frpc && \
   chmod +x /frp/usr/bin/frps
