requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /stern

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /stern/usr/bin && \
   curl -L https://github.com/wercker/stern/releases/download/${PACKAGE_VERSION}/stern_linux_{{.Values.arch}} -o /stern/usr/bin/stern && \
   chmod +x /stern/usr/bin/stern
