image: "quay.io/mocaccino/micro:master"

package_dir: /kubectl

prelude:
- luet install libs/libressl utils/ca-certificates utils/curl libs/zlib

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /kubectl/usr/bin && \
   curl -L https://storage.googleapis.com/kubernetes-release/release/v${PACKAGE_VERSION}/bin/linux/amd64/kubectl -o /kubectl/usr/bin/kubectl && \
   chmod +x /kubectl/usr/bin/kubectl
