name: Build packages

on:
  push:
    branches: [ master,test ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENCODED_KUBECONFIG: ${{ secrets.KUBECONFIG }}
      MINIO_API_URL: ${{ secrets.MINIO_API_URL }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      IMAGE_REPOSITORY: quay.io/mocaccinocache/extra-amd64-cache
      BUCKET: mocaccino-extra
      NAMESPACE: workload-mocaccino-extra
      TREE_DIR: "amd64 multi-arch"
      DOCKER_REGISTRY: quay.io
      DOCKER_USER: ${{ secrets.QUAY_USERNAME }}
      DOCKER_PASS: ${{ secrets.QUAY_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - uses: fkirc/skip-duplicate-actions@master
    - run: |
        git fetch --prune --unshallow
    - name: Installing dependencies
      run: |
        curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
        sudo luet install -y repository/mocaccino-extra-stable
        sudo luet install -y system/luet-extensions system/luet-devkit utils/jq net-fs/minio-client container/kubectl
        sudo curl -L https://raw.githubusercontent.com/Luet-lab/extensions/master/extensions/k8s-build-scheduler/luet-k8s-build-scheduler -o /usr/bin/luet-k8s-build-scheduler
    - name: Build repository 🔧
      run: |
        export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
        export REF=$GITHUB_SHA
        export GITHUB_REPO=$GITHUB_REPOSITORY
        echo "$ENCODED_KUBECONFIG" | base64 -d > $KUBECONFIG
        kubectl create namespace $NAMESPACE || true
        luet k8s-build-scheduler
    - name: Create repository 🔧
      run: |
        BUILD_PHASE=false CREATE_PHASE=true luet k8s-build-scheduler
    - name: Push to stable repository 🚀
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mc mirror --overwrite --remove minio-ci/$BUCKET minio-ci/$BUCKET-stable