{{ $org:= ( index .Values.labels "github.owner" ) }}
{{ $repo:= ( index .Values.labels "github.repo" ) }}
{{ $opts:= dict "org" $org "repo" $repo }}
{{ template "golang_build" $opts}}
-  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   cd go/src/github.com/{{$org}}/{{$repo}}/ && git checkout "v${PACKAGE_VERSION}" -b build && go build -o {{.Values.name}} \
   && mv {{.Values.name}} /output/usr/bin/{{.Values.name}}
- chmod +x /output/usr/bin/{{ .Values.name }}